apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"cassandra"},"name":"cassandra","namespace":"default","selfLink":"/api/v1/namespaces/default/services/cassandra"},"spec":{"ports":[{"name":"port-1","port":9042,"protocol":"TCP"},{"name":"port-2","port":9142,"protocol":"TCP"}],"selector":{"app":"cassandra"},"sessionAffinity":"None","type":"NodePort"},"status":{"loadBalancer":{}}}
  creationTimestamp: null
  labels:
    app: cassandra
  name: cassandra
  selfLink: /api/v1/namespaces/default/services/cassandra
spec:
  ports:
  - name: port-1
    port: 9042
    protocol: TCP
    targetPort: 9042
  selector:
    app: cassandra
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
