apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: cassandra
  name: cassandra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - image: cassandra:2.1
        env:
        - name: CASSANDRA_LISTEN_ADDRESS
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: IfNotPresent
        name: cassandra
        volumeMounts:
        - mountPath: /var/lib/cassandra
          name: cassandra-persistent-storage
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cassandra-persistent-storage
        persistentVolumeClaim:
          claimName: cassandra-pv-claim
