apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: payloadviewer
  name: payloadviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payloadviewer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payloadviewer
    spec:
      containers:
      - image: gcr.io/MY_PROJECT/payload-viewer:v3
        imagePullPolicy: IfNotPresent
        name: payloadviewer
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
