apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: payloadviewer
  name: payloadviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payloadviewer
  template:
    metadata:
      labels:
        app: payloadviewer
    spec:
      containers:
      - image: gcr.io/MY_PROJECT/payload-viewer:v3
        name: payloadviewer
