apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payloadviewer
  name: payloadviewer
  selfLink: /api/v1/namespaces/default/services/payloadviewer
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31407
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: payloadviewer
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
